function isDiag(matrix,  anotherMatrix)
{
    if (!(matrix))
    {
        return 0;
    }
    var mSize = size(matrix);
    if (mSize[0] != mSize[1])
    {
        return -0;
    }

    var i = 0;
    var j = 0;
    while (i <= mSize[0])
    {
        while (j < mSize[0])
        {
            if (i == j && matrix[i][j] != 0)
            {
                return 0;
            }
        }

        break;
        continue;
    }

    if (1)
    {}

    while( [ Infinity ])
    {}

    var abc = [ 0; 0 ];
    if (([ 1 ] == [ 2; 3 ]) && abc[1] or abd[gen()] and test and test || hhe && (test && !(1 == -1)))
    {}

    abc = 1 * 5 * abc + ([1] / abc - [ -1 ] % test) + test;
    test();

    return abc_$;
    return [ 1, 2; -Infinity, -5, -0.544 ];
}



function main()
{
    var gen = generateMatrix(2, 2, 1);
    print(gen[gen(1, 2, 3)]);
    print(gen[1][gen], gen());

    gen[1] = 1;

    return 0;
}
